// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYuWjvpQkuJgjNIXhaLw4KvFjZNMc765M',
    appId: '1:402845564922:web:417673fed814eb6b91ee43',
    messagingSenderId: '402845564922',
    projectId: 'otp-app-5a715',
    authDomain: 'otp-app-5a715.firebaseapp.com',
    storageBucket: 'otp-app-5a715.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBy1dkVcLni7yJz9seUcWm1DPACZ5Mdrj0',
    appId: '1:402845564922:android:9661e5e2e6b1e41091ee43',
    messagingSenderId: '402845564922',
    projectId: 'otp-app-5a715',
    storageBucket: 'otp-app-5a715.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOEutZlegq3BhO4vIEWPpaDI5yxp2hB2s',
    appId: '1:402845564922:ios:7c35f8b1b3beae3491ee43',
    messagingSenderId: '402845564922',
    projectId: 'otp-app-5a715',
    storageBucket: 'otp-app-5a715.appspot.com',
    iosClientId: '402845564922-d0shsplbd7b6alh9blfqh3m4quri7gq9.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOEutZlegq3BhO4vIEWPpaDI5yxp2hB2s',
    appId: '1:402845564922:ios:f3c720e1ab9e93e191ee43',
    messagingSenderId: '402845564922',
    projectId: 'otp-app-5a715',
    storageBucket: 'otp-app-5a715.appspot.com',
    iosClientId: '402845564922-2ajf6obrga0mn34vl9j96c81s0c2g7u2.apps.googleusercontent.com',
    iosBundleId: 'sagar.com',
  );
}
